### ISSUE TITLE
Problem with a command

### ISSUE THREAD

**Issue by eporsch** [ahmedmagds/Microbial-Genomics-Journey-Workshop-2023#2]
Hi Ahmed,

In the 'Mash' section of Session 2, the following command block is listed:

conda activate mash
cd ~/MGJW/problem_set1/fastq
cat mockdna_R1.fastq mockdna_R2.fastq > mockdna_reads.fastq
gunzip ../RefSeqSketches.msh.gz
mash screen -w -p 8 ../RefSeqSketches.msh mockdna_reads.fastq > mockdna_screen_winning.tab
less mock_screen_winning.tab
sort -gr mockdna_screen_winning.tab > mockdna_screen_winning_sorted.tab
less mockdna_screen_winning_sorted.tab

The 6th line down should be "less mockdna_screen_winning.tab" 

I am learning to use GitHub!

Eric

**Comment by eporsch** [comment]
Also just an FYI, the second bullet point of Part 2 of Problem Set 2 lists the files as ".fna" when they should be listed as ".fasta"

**Comment by ahmedmagds** [comment]
Thanks, Eric, updated!
